---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional, otherwise uses default branch)'
        required: false
        default: ''

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    # Only on main repository (don't publish on forks)
    if: github.repository_owner == 'wetransform'

    uses: wetransform/gha-workflows/.github/workflows/mise-publish.yml@32c81994f6677a00a9d5f1fec6338ad15e641fe0 # v4.6.0
    with:
      default-branch: master
    secrets: inherit
