---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
        default: false

concurrency:
  # only run one release at a time to avoid conflicts
  group: release-${{ github.ref }}

jobs:
  release:
    # Only on main repository (don't release on forks)
    if: github.repository_owner == 'wetransform'

    uses: wetransform/gha-workflows/.github/workflows/mise-release.yml@32aadc152107f12c1671d09290b06bdb88642d1c # v4.2.2
    with:
      dry-run: ${{ inputs.dryRun }}
    secrets: inherit
